version: '3.1'
services:
  boot-admin:
    restart: always
    image: boot-admin:v3
    environment:
      - JAVA_OPTS=-server -Dspring.profiles.active=prod
      - TZ=Asia/Shanghai
    ports:
      - 8088:8088
    container_name: boot-admin
    networks:
      - docker-net
networks:
  docker-net:
    external: true
